// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// Client skeleton

#include <memory>
#include <staff/utils/Log.h>
#include <staff/common/logoperators.h>
#include <staff/common/Exception.h>
#include <staff/client/ServiceFactory.h>
#include "wsOCR1.h"
#include <iostream>
#include "strHex.h"

using namespace std;

int main(int /*nArgs*/, const char* /*paszArgs*/[])
{



	string tdoOCRResult;

  try
  {
	   std::auto_ptr< ::wsOCR1 > pwsOCR1(::staff::ServiceFactory::Inst().GetService< ::wsOCR1 >("http://54.225.96.208:9090/axis2/services/wsOCR1"));

    STAFF_ASSERT(pwsOCR1.get(), "Cannot get client for service wsOCR1!");

    // Invoke Your service here:

     string fileAddress="c:\\code\\Tesseract-OCR_setup\\ocrtest.jpg";

     tdoOCRResult = pwsOCR1->doOCR(fileAddress);
	 tdoOCRResult=hex2str(tdoOCRResult);
     //staff::LogInfo() << "doOCR result: " << tdoOCRResult;
  }
  STAFF_CATCH_ALL

	  	 // cout<<tdoOCRResult;
		 cout<<"done!"<<endl;
          cout<<tdoOCRResult.c_str();

	  char cc;
  cin>>cc;

  return 0;
}

