// This file generated by staff_codegen
// For more information please visit: http://code.google.com/p/staff/
// DO NOT EDIT

#ifndef _wsOCRProxy_h_
#define _wsOCRProxy_h_

#include <staff/client/ServiceClient.h>
#include "wsOCR.h"


//! Proxy for component service wsOCR
class wsOCRProxy: public wsOCR
{
public:
  wsOCRProxy();
  virtual ~wsOCRProxy();
  void Init(const std::string& sServiceUri, const std::string& sSessionId, const std::string& sInstanceId);
  void Deinit();
  virtual staff::ServiceClient* GetClient();
  double sendClientID(double clientID);
  std::string receiveContent(int linker, int flag);
  void sendContent(std::string content, int linker, int flag);
  void sendFile(std::string fileContent, std::string fileAddress);
  std::string sendFile(std::string fileContent);
  int sendFileClient(std::string fileContent);
  std::string receiveFile(std::string fileAddress);
  void sendFileInfo(std::string filename, std::string fileInfo);
  std::string receiveFileInfo(std::string filename);
  void doOCR(std::string fileAddress);
  void doOCR(double clientID);
  std::string receiveOCR(std::string fileAddress);
  std::string perform(std::string AppData);
private:
  mutable staff::ServiceClient m_tClient;
  std::string m_sServiceUri;
};


namespace staff
{
  class DataObject;
}

#endif

